# Generated by Django 2.0.6 on 2020-05-14 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='emp.BaseModel')),
                ('dep_name', models.CharField(max_length=128)),
                ('location', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': '部门',
                'verbose_name_plural': '部门',
                'db_table': 'bz_department',
            },
            bases=('emp.basemodel',),
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='emp.BaseModel')),
                ('emp_name', models.CharField(max_length=128)),
                ('gender', models.SmallIntegerField(choices=[(0, 'male'), (1, 'female'), (2, 'secret')])),
                ('salary', models.DecimalField(decimal_places=2, max_digits=8)),
                ('dep', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='emp.Department')),
            ],
            options={
                'verbose_name': '员工',
                'verbose_name_plural': '员工',
                'db_table': 'employees',
            },
            bases=('emp.basemodel',),
        ),
    ]
